name: Build and Deploy
description: Build and deploy a static React webapp to GitHub Pages
inputs:
  repository:
    description: 'The repository name'
    required: true
  branch:
    description: 'The branch name'
    required: true
  path:
    description: 'The path to the React app'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
